
'use client';

import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { DashboardHeader } from '@/components/dashboard-header';
import { Calendar, DollarSign, MapPin, Tractor, Phone, Mail, Star, Clock, Mountain } from 'lucide-react';
import { useState } from 'react';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import { Badge } from '@/components/ui/badge';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';

type JobPost = {
  farmerName: string;
  location: string; // "Taluk, District"
  acres: number;
  landDetails: string;
  workerExpectations: string;
  workHours: string;
  salary: number;
  farmerEmail:string;
  farmerPhone: string;
  farmerRating: number;
  farmerImage: string;
  farmerImageHint: string;
};

const jobPosts: JobPost[] = [
  // Coimbatore
  { farmerName: 'Kumar (குமார்)', location: 'Pollachi, Coimbatore (பொள்ளாச்சி, கோயம்புத்தூர்)', acres: 10, landDetails: 'Coconut Cultivation (தென்னை சாகுபடி)', workerExpectations: 'Climb coconut trees and pluck coconuts (தென்னை மரம் ஏறி தேங்காய் பறிக்க வேண்டும்)', workHours: '8 Hours (8 மணி நேரம்)', salary: 800, farmerEmail: 'kumar.pollachi@example.com', farmerPhone: '9876543210', farmerRating: 4.7, farmerImage: 'https://placehold.co/100x100.png?text=கு', farmerImageHint: 'farmer portrait' },
  { farmerName: 'Raja (ராஜா)', location: 'Pollachi, Coimbatore (பொள்ளாச்சி, கோயம்புத்தூர்)', acres: 5, landDetails: 'Vegetable Garden (காய்கறி தோட்டம்)', workerExpectations: 'Weeding and vegetable picking (களை எடுக்க ও காய்கறி பறிக்க வேண்டும்)', workHours: '7 Hours (7 மணி நேரம்)', salary: 600, farmerEmail: 'raja.pollachi@example.com', farmerPhone: '9876543211', farmerRating: 4.5, farmerImage: 'https://placehold.co/100x100.png?text=ரா', farmerImageHint: 'smiling farmer' },
  { farmerName: 'Anbu (அன்பு)', location: 'Pollachi, Coimbatore (பொள்ளாச்சி, கோயம்புத்தூர்)', acres: 15, landDetails: 'Banana Plantation (வாழைத் தோட்டம்)', workerExpectations: 'Cut and maintain banana bunches (வாழைத்தார்களை வெட்டி, பராமரிக்க வேண்டும்)', workHours: '8 Hours (8 மணி நேரம்)', salary: 750, farmerEmail: 'anbu.pollachi@example.com', farmerPhone: '9876543212', farmerRating: 4.8, farmerImage: 'https://placehold.co/100x100.png?text=அ', farmerImageHint: 'man in farm' },
  { farmerName: 'Sankar (சங்கர்)', location: 'Pollachi, Coimbatore (பொள்ளாச்சி, கோயம்புத்தூர்)', acres: 8, landDetails: 'Coconut and Banana (தென்னை மற்றும் வாழை)', workerExpectations: 'Irrigation management and fertilization (பாசன மேலாண்மை மற்றும் உரம் வைத்தல்)', workHours: '9 Hours (9 மணி நேரம்)', salary: 850, farmerEmail: 'sankar.pollachi@example.com', farmerPhone: '9876543213', farmerRating: 4.6, farmerImage: 'https://placehold.co/100x100.png?text=ச', farmerImageHint: 'farmer working' },
  { farmerName: 'Velu (வேலு)', location: 'Pollachi, Coimbatore (பொள்ளாச்சி, கோயம்புத்தூர்)', acres: 12, landDetails: 'Sugarcane Cultivation (கரும்பு சாகுபடி)', workerExpectations: 'Cut sugarcane and load it onto the tractor (கரும்பு வெட்டி, டிராக்டரில் ஏற்ற வேண்டும்)', workHours: '8 Hours (8 மணி நேரம்)', salary: 900, farmerEmail: 'velu.pollachi@example.com', farmerPhone: '9876543214', farmerRating: 4.9, farmerImage: 'https://placehold.co/100x100.png?text=வே', farmerImageHint: 'farmer with sugarcane' },

  { farmerName: 'Selvam (செல்வம்)', location: 'Mettupalayam, Coimbatore (மேட்டுப்பாளையம், கோயம்புத்தூர்)', acres: 8, landDetails: 'Areca Nut Grove (பாக்கு தோப்பு)', workerExpectations: 'Climb areca nut trees and pluck nuts (பாக்கு மரம் ஏறி, பாக்கு பறிக்க வேண்டும்)', workHours: '8 Hours (8 மணி நேரம்)', salary: 850, farmerEmail: 'selvam.m@example.com', farmerPhone: '9876543217', farmerRating: 4.6, farmerImage: 'https://placehold.co/100x100.png?text=செ', farmerImageHint: 'man climbing tree' },
  { farmerName: 'Murugan (முருகன்)', location: 'Mettupalayam, Coimbatore (மேட்டுப்பாளையம், கோயம்புத்தூர்)', acres: 10, landDetails: 'Banana Cultivation (வாழை சாகுபடி)', workerExpectations: 'Banana planting and maintenance (வாழை நடவு மற்றும் பராமரிப்பு)', workHours: '7 Hours (7 மணி நேரம்)', salary: 700, farmerEmail: 'murugan.m@example.com', farmerPhone: '9876543218', farmerRating: 4.8, farmerImage: 'https://placehold.co/100x100.png?text=மு', farmerImageHint: 'man in banana farm' },
  { farmerName: 'Karthi (கார்த்தி)', location: 'Mettupalayam, Coimbatore (மேட்டுப்பாளையம், கோயம்புத்தூர்)', acres: 6, landDetails: 'Turmeric Cultivation (மஞ்சள் சாகுபடி)', workerExpectations: 'Turmeric harvesting and processing (மஞ்சள் அறுவடை மற்றும் பதப்படுத்துதல்)', workHours: '8 Hours (8 மணி நேரம்)', salary: 750, farmerEmail: 'karthi.m@example.com', farmerPhone: '9876543219', farmerRating: 4.7, farmerImage: 'https://placehold.co/100x100.png?text=கா', farmerImageHint: 'farmer with turmeric' },
  { farmerName: 'Pandi (பாண்டி)', location: 'Mettupalayam, Coimbatore (மேட்டுப்பாளையம், கோயம்புத்தூர்)', acres: 12, landDetails: 'Vegetable Farm (காய்கறி பண்ணை)', workerExpectations: 'Pesticide spraying and maintenance (பூச்சி மருந்து தெளித்தல் மற்றும் பராமரிப்பு)', workHours: '7 Hours (7 மணி நேரம்)', salary: 680, farmerEmail: 'pandi.m@example.com', farmerPhone: '9876543220', farmerRating: 4.5, farmerImage: 'https://placehold.co/100x100.png?text=பா', farmerImageHint: 'farmer spraying' },
  { farmerName: 'Ganesan (கணேசன்)', location: 'Mettupalayam, Coimbatore (மேட்டுப்பாளையம், கோயம்புத்தூர்)', acres: 4, landDetails: 'Flower Cultivation (பூக்கள் சாகுபடி)', workerExpectations: 'Nursery setup, flower picking (நாற்றங்கால் அமைத்தல், பூ பறித்தல்)', workHours: '6 Hours (6 மணி நேரம்)', salary: 550, farmerEmail: 'ganesan.m@example.com', farmerPhone: '9876543221', farmerRating: 4.9, farmerImage: 'https://placehold.co/100x100.png?text=க', farmerImageHint: 'man with flowers' },

  // Madurai
  { farmerName: 'Pandiyan (பாண்டியன்)', location: 'Thirumangalam, Madurai (திருமங்கலம், மதுரை)', acres: 12, landDetails: 'Paddy Cultivation (நெல் சாகுபடி)', workerExpectations: 'Planting, weeding, and harvesting (நடவு, களையெடுப்பு மற்றும் அறுவடை)', workHours: '8 Hours (8 மணி நேரம்)', salary: 700, farmerEmail: 'pandiyan.t@example.com', farmerPhone: '9765432109', farmerRating: 4.8, farmerImage: 'https://placehold.co/100x100.png?text=பா', farmerImageHint: 'farmer in paddy field' },
  { farmerName: 'Meenatchi (மீனாட்சி)', location: 'Thirumangalam, Madurai (திருமங்கலம், மதுரை)', acres: 3, landDetails: 'Jasmine Flower Garden (மல்லிகை பூ தோட்டம்)', workerExpectations: 'Pick flowers daily and make garlands (தினமும் பூ பறித்து மாலையாக கட்ட வேண்டும்)', workHours: '6 Hours (6 மணி நேரம்)', salary: 500, farmerEmail: 'meenatchi.t@example.com', farmerPhone: '9765432110', farmerRating: 4.9, farmerImage: 'https://placehold.co/100x100.png?text=மீ', farmerImageHint: 'woman with jasmine' },
  { farmerName: 'Karuppasamy (கருப்பசாமி)', location: 'Thirumangalam, Madurai (திருமங்கலம், மதுரை)', acres: 10, landDetails: 'Sugarcane Mill (கரும்பு ஆலை)', workerExpectations: 'Cut sugarcane and send it to the mill (கரும்பு வெட்டி ஆலைக்கு அனுப்ப வேண்டும்)', workHours: '9 Hours (9 மணி நேரம்)', salary: 850, farmerEmail: 'karuppasamy.t@example.com', farmerPhone: '9765432111', farmerRating: 4.6, farmerImage: 'https://placehold.co/100x100.png?text=க', farmerImageHint: 'man with sugarcane' },
  { farmerName: 'Muthu (முத்து)', location: 'Thirumangalam, Madurai (திருமங்கலம், மதுரை)', acres: 7, landDetails: 'Banana and Vegetables (வாழை மற்றும் காய்கறிகள்)', workerExpectations: 'Farm maintenance and marketing (பண்ணையை பராமரித்தல் மற்றும் சந்தைப்படுத்துதல்)', workHours: '8 Hours (8 மணி நேரம்)', salary: 650, farmerEmail: 'muthu.t@example.com', farmerPhone: '9765432112', farmerRating: 4.7, farmerImage: 'https://placehold.co/100x100.png?text=மு', farmerImageHint: 'farmer with vegetables' },
  { farmerName: 'Veeran (வீரன்)', location: 'Thirumangalam, Madurai (திருமங்கலம், மதுரை)', acres: 15, landDetails: 'Cotton Cultivation (பருத்தி சாகுபடி)', workerExpectations: 'Cotton picking and ginning (பருத்தி எடுத்தல் மற்றும் பஞ்சு பிரித்தல்)', workHours: '8 Hours (8 மணி நேரம்)', salary: 720, farmerEmail: 'veeran.t@example.com', farmerPhone: '9765432113', farmerRating: 4.5, farmerImage: 'https://placehold.co/100x100.png?text=வீ', farmerImageHint: 'farmer in cotton field' },

  { farmerName: 'Ramu (ராமு)', location: 'Usilampatti, Madurai (உசிலம்பட்டி, மதுரை)', acres: 20, landDetails: 'Mango Grove (மாந்தோப்பு)', workerExpectations: 'Mango picking and sorting (மாங்காய் பறித்தல், தரம் பிரித்தல்)', workHours: '8 Hours (8 மணி நேரம்)', salary: 780, farmerEmail: 'ramu.u@example.com', farmerPhone: '9765432116', farmerRating: 4.6, farmerImage: 'https://placehold.co/100x100.png?text=ரா', farmerImageHint: 'farmer with mangoes' },
  { farmerName: 'Somu (சோமு)', location: 'Usilampatti, Madurai (உசிலம்பட்டி, மதுரை)', acres: 10, landDetails: 'Chilli Garden (மிளகாய் தோட்டம்)', workerExpectations: 'Chilli picking and drying (மிளகாய் பறித்து, காய வைத்தல்)', workHours: '7 Hours (7 மணி நேரம்)', salary: 670, farmerEmail: 'somu.u@example.com', farmerPhone: '9765432117', farmerRating: 4.5, farmerImage: 'https://placehold.co/100x100.png?text=சோ', farmerImageHint: 'farmer with chillies' },
  { farmerName: 'Lakshmi (லட்சுமி)', location: 'Usilampatti, Madurai (உசிலம்பட்டி, மதுரை)', acres: 6, landDetails: 'Growing Greens (கீரை வகைகள் பயிரிடுதல்)', workerExpectations: 'Harvesting and bundling greens (கீரை அறுவடை மற்றும் கட்டுதல்)', workHours: '6 Hours (6 மணி நேரம்)', salary: 520, farmerEmail: 'lakshmi.u@example.com', farmerPhone: '9765432118', farmerRating: 4.8, farmerImage: 'https://placehold.co/100x100.png?text=ல', farmerImageHint: 'woman with greens' },
  { farmerName: 'Perumal (பெருமாள்)', location: 'Usilampatti, Madurai (உசிலம்பட்டி, மதுரை)', acres: 14, landDetails: 'Groundnut Cultivation (நிலக்கடலை சாகுபடி)', workerExpectations: 'Harvest and dry groundnuts (நிலக்கடலை அறுவடை செய்து காய வைத்தல்)', workHours: '8 Hours (8 மணி நேரம்)', salary: 730, farmerEmail: 'perumal.u@example.com', farmerPhone: '9765432119', farmerRating: 4.7, farmerImage: 'https://placehold.co/100x100.png?text=பெ', farmerImageHint: 'farmer with groundnuts' },
  { farmerName: 'Devan (தேவன்)', location: 'Usilampatti, Madurai (உசிலம்பட்டி, மதுரை)', acres: 11, landDetails: 'Goat Farm (ஆட்டுப் பண்ணை)', workerExpectations: 'Herding and caring for goats (ஆடுகளை மேய்த்தல் மற்றும் பராமரித்தல்)', workHours: '9 Hours (9 மணி நேரம்)', salary: 700, farmerEmail: 'devan.u@example.com', farmerPhone: '9765432120', farmerRating: 4.6, farmerImage: 'https://placehold.co/100x100.png?text=தே', farmerImageHint: 'man with goats' },

  // Tiruchirappalli
  { farmerName: 'Kaveri Nathan (காவேரி நாதன்)', location: 'Lalgudi, Tiruchirappalli (லால்குடி, திருச்சிராப்பள்ளி)', acres: 25, landDetails: 'Paddy & Sugarcane (நெல் மற்றும் கரும்பு)', workerExpectations: 'Machine operation for harvesting (அறுவடைக்கு இயந்திரம் இயக்குதல்)', workHours: '9 Hours (9 மணி நேரம்)', salary: 950, farmerEmail: 'kaveri.lalgudi@email.com', farmerPhone: '9988776655', farmerRating: 4.9, farmerImage: 'https://placehold.co/100x100.png?text=கா', farmerImageHint: 'farmer portrait' },
  { farmerName: 'Balamurugan (பாலமுருகன்)', location: 'Lalgudi, Tiruchirappalli (லால்குடி, திருச்சிராப்பள்ளி)', acres: 15, landDetails: 'Banana Plantation (வாழைத் தோட்டம்)', workerExpectations: 'Planting and maintaining banana trees (வாழை மரங்களை நட்டு பராமரித்தல்)', workHours: '8 Hours (8 மணி நேரம்)', salary: 720, farmerEmail: 'balamurugan.lalgudi@email.com', farmerPhone: '9988776653', farmerRating: 4.7, farmerImage: 'https://placehold.co/100x100.png?text=பா', farmerImageHint: 'farmer in banana plantation' },
  { farmerName: 'Chitra (சித்ரா)', location: 'Lalgudi, Tiruchirappalli (லால்குடி, திருச்சிராப்பள்ளி)', acres: 10, landDetails: 'Vegetable Farm (காய்கறி பண்ணை)', workerExpectations: 'Sowing seeds, weeding, and harvesting vegetables (விதை விதைத்தல், களையெடுத்தல், காய்கறி அறுவடை)', workHours: '7 Hours (7 மணி நேரம்)', salary: 620, farmerEmail: 'chitra.lalgudi@email.com', farmerPhone: '9988776652', farmerRating: 4.8, farmerImage: 'https://placehold.co/100x100.png?text=சி', farmerImageHint: 'woman with vegetables' },
  { farmerName: 'Dharma (தர்மா)', location: 'Lalgudi, Tiruchirappalli (லால்குடி, திருச்சிராப்பள்ளி)', acres: 20, landDetails: 'Paddy Fields (நெல் வயல்கள்)', workerExpectations: 'Operating a tractor for ploughing (உழுவதற்கு டிராக்டர் இயக்குதல்)', workHours: '8 Hours (8 மணி நேரம்)', salary: 850, farmerEmail: 'dharma.lalgudi@email.com', farmerPhone: '9988776651', farmerRating: 4.6, farmerImage: 'https://placehold.co/100x100.png?text=த', farmerImageHint: 'man on tractor' },
  { farmerName: 'Eswari (ஈஸ்வரி)', location: 'Lalgudi, Tiruchirappalli (லால்குடி, திருச்சிராப்பள்ளி)', acres: 5, landDetails: 'Groundnut Cultivation (நிலக்கடலை சாகுபடி)', workerExpectations: 'Harvesting and drying groundnuts (நிலக்கடலை அறுவடை செய்து காயவைத்தல்)', workHours: '8 Hours (8 மணி நேரம்)', salary: 650, farmerEmail: 'eswari.lalgudi@email.com', farmerPhone: '9988776650', farmerRating: 4.9, farmerImage: 'https://placehold.co/100x100.png?text=ஈ', farmerImageHint: 'woman with groundnuts' },

  { farmerName: 'Sriranganathan (ஸ்ரீரங்கநாதன்)', location: 'Srirangam, Tiruchirappalli (ஸ்ரீரங்கம், திருச்சிராப்பள்ளி)', acres: 4, landDetails: 'Flower & Banana Leaf (பூ மற்றும் வாழை இலை)', workerExpectations: 'Daily flower plucking and leaf cutting (தினசரி பூ பறித்தல் மற்றும் இலை வெட்டுதல்)', workHours: '6 Hours (6 மணி நேரம்)', salary: 550, farmerEmail: 'sri.ranga@email.com', farmerPhone: '9988776654', farmerRating: 4.8, farmerImage: 'https://placehold.co/100x100.png?text=ஸ்ரீ', farmerImageHint: 'man with flowers' },
  { farmerName: 'Vasan (வாசன்)', location: 'Srirangam, Tiruchirappalli (ஸ்ரீரங்கம், திருச்சிராப்பள்ளி)', acres: 8, landDetails: 'Betel Leaf Garden (வெற்றிலை கொடிக்கால்)', workerExpectations: 'Maintaining betel vines and plucking leaves (வெற்றிலை கொடிகளை பராமரித்து, இலை பறித்தல்)', workHours: '7 Hours (7 மணி நேரம்)', salary: 600, farmerEmail: 'vasan.srirangam@email.com', farmerPhone: '9988776649', farmerRating: 4.7, farmerImage: 'https://placehold.co/100x100.png?text=வா', farmerImageHint: 'farmer with betel leaves' },
  { farmerName: 'Usha (உஷா)', location: 'Srirangam, Tiruchirappalli (ஸ்ரீரங்கம், திருச்சிராப்பள்ளி)', acres: 3, landDetails: 'Vegetable Garden for Temple (கோயிலுக்கான காய்கறி தோட்டம்)', workerExpectations: 'Organic vegetable cultivation for temple offerings (கோயில் பிரசாதத்திற்காக இயற்கை காய்கறி சாகுபடி)', workHours: '6 Hours (6 மணி நேரம்)', salary: 580, farmerEmail: 'usha.srirangam@email.com', farmerPhone: '9988776648', farmerRating: 5.0, farmerImage: 'https://placehold.co/100x100.png?text=உ', farmerImageHint: 'woman in garden' },
  { farmerName: 'Thirumalai (திருமலை)', location: 'Srirangam, Tiruchirappalli (ஸ்ரீரங்கம், திருச்சிராப்பள்ளி)', acres: 10, landDetails: 'Sugarcane Field (கரும்பு வயல்)', workerExpectations: 'Sugarcane cutting and loading (கரும்பு வெட்டி ஏற்றுதல்)', workHours: '8 Hours (8 மணி நேரம்)', salary: 880, farmerEmail: 'thirumalai.srirangam@email.com', farmerPhone: '9988776647', farmerRating: 4.6, farmerImage: 'https://placehold.co/100x100.png?text=தி', farmerImageHint: 'man cutting sugarcane' },
  { farmerName: 'Janani (ஜனனி)', location: 'Srirangam, Tiruchirappalli (ஸ்ரீரங்கம், திருச்சிராப்பள்ளி)', acres: 2, landDetails: 'Herbal Garden (மூலிகை தோட்டம்)', workerExpectations: 'Growing and maintaining medicinal herbs (மருத்துவ மூலிகைகளை வளர்த்து பராமரித்தல்)', workHours: '5 Hours (5 மணி நேரம்)', salary: 500, farmerEmail: 'janani.srirangam@email.com', farmerPhone: '9988776646', farmerRating: 4.9, farmerImage: 'https://placehold.co/100x100.png?text=ஜ', farmerImageHint: 'woman with herbs' },
  
  // Salem
  { farmerName: 'Mangai Kumar (மாங்காய் குமார்)', location: 'Salem, Salem (சேலம், சேலம்)', acres: 30, landDetails: 'Mango Orchard (மாந்தோப்பு)', workerExpectations: 'Mango harvesting, grading, and packing (மாங்காய் அறுவடை, தரம் பிரித்தல், கட்டுதல்)', workHours: '8 Hours (8 மணி நேரம்)', salary: 800, farmerEmail: 'mango.kumar@email.com', farmerPhone: '9776655443', farmerRating: 4.7, farmerImage: 'https://placehold.co/100x100.png?text=மா', farmerImageHint: 'farmer with mangoes' },
  { farmerName: 'Elango (இளங்கோ)', location: 'Salem, Salem (சேலம், சேலம்)', acres: 10, landDetails: 'Sandalwood Plantation (சந்தன மர தோட்டம்)', workerExpectations: 'Maintenance and security of sandalwood trees (சந்தன மரங்களை பராமரித்தல் மற்றும் பாதுகாத்தல்)', workHours: '9 Hours (9 மணி நேரம்)', salary: 900, farmerEmail: 'elango.salem@email.com', farmerPhone: '9776655441', farmerRating: 4.8, farmerImage: 'https://placehold.co/100x100.png?text=இ', farmerImageHint: 'man in a grove' },
  { farmerName: 'Ramya (ரம்யா)', location: 'Salem, Salem (சேலம், சேலம்)', acres: 7, landDetails: 'Coffee Estate (காபி எஸ்டேட்)', workerExpectations: 'Coffee bean picking and processing (காபி கொட்டை பறித்தல் மற்றும் பதப்படுத்துதல்)', workHours: '8 Hours (8 மணி நேரம்)', salary: 750, farmerEmail: 'ramya.salem@email.com', farmerPhone: '9776655440', farmerRating: 4.6, farmerImage: 'https://placehold.co/100x100.png?text=ர', farmerImageHint: 'woman picking coffee beans' },
  { farmerName: 'Senthil (செந்தில்)', location: 'Salem, Salem (சேலம், சேலம்)', acres: 12, landDetails: 'Silver Oak Trees (சில்வர் ஓக் மரங்கள்)', workerExpectations: 'Pruning and managing silver oak trees (சில்வர் ஓக் மரங்களை கత్తిரித்து பராமரித்தல்)', workHours: '7 Hours (7 மணி நேரம்)', salary: 680, farmerEmail: 'senthil.salem@email.com', farmerPhone: '9776655439', farmerRating: 4.5, farmerImage: 'https://placehold.co/100x100.png?text=செ', farmerImageHint: 'man with axe' },
  { farmerName: 'Vanaja (வனஜா)', location: 'Salem, Salem (சேலம், சேலம்)', acres: 5, landDetails: 'Jasmine and Rose Garden (மல்லிகை மற்றும் ரோஜா தோட்டம்)', workerExpectations: 'Flower picking and stringing garlands (பூக்கள் பறித்து மாலை கட்டுதல்)', workHours: '6 Hours (6 மணி நேரம்)', salary: 550, farmerEmail: 'vanaja.salem@email.com', farmerPhone: '9776655438', farmerRating: 4.9, farmerImage: 'https://placehold.co/100x100.png?text=வ', farmerImageHint: 'woman with flowers' },

  { farmerName: 'Sago Selvi (ஜவ்வரிசி செல்வி)', location: 'Attur, Salem (ஆத்தூர், சேலம்)', acres: 15, landDetails: 'Tapioca farm (மரவள்ளிக்கிழங்கு பண்ணை)', workerExpectations: 'Harvesting tapioca and processing for sago (மரவள்ளி அறுவடை மற்றும் ஜவ்வரிசி தயாரிப்பு)', workHours: '8 Hours (8 மணி நேரம்)', salary: 700, farmerEmail: 'sago.selvi@email.com', farmerPhone: '9776655442', farmerRating: 4.6, farmerImage: 'https://placehold.co/100x100.png?text=ஜ', farmerImageHint: 'woman with tapioca' },
  { farmerName: 'Kandasamy (கந்தசாமி)', location: 'Attur, Salem (ஆத்தூர், சேலம்)', acres: 20, landDetails: 'Sugarcane and Cotton (கரும்பு மற்றும் பருத்தி)', workerExpectations: 'Harvesting sugarcane and picking cotton (கரும்பு வெட்டுதல் மற்றும் பருத்தி எடுத்தல்)', workHours: '9 Hours (9 மணி நேரம்)', salary: 820, farmerEmail: 'kandasamy.attur@email.com', farmerPhone: '9776655437', farmerRating: 4.5, farmerImage: 'https://placehold.co/100x100.png?text=க', farmerImageHint: 'farmer in field' },
  { farmerName: 'Leela (லீலா)', location: 'Attur, Salem (ஆத்தூர், சேலம்)', acres: 8, landDetails: 'Paddy Fields (நெல் வயல்கள்)', workerExpectations: 'Transplanting paddy seedlings and weeding (நெல் நாற்று நடுதல் மற்றும் களையெடுத்தல்)', workHours: '7 Hours (7 மணி நேரம்)', salary: 600, farmerEmail: 'leela.attur@email.com', farmerPhone: '9776655436', farmerRating: 4.8, farmerImage: 'https://placehold.co/100x100.png?text=லீ', farmerImageHint: 'woman in paddy field' },
  { farmerName: 'Nallasivam (நல்லசிவம்)', location: 'Attur, Salem (ஆத்தூர், சேலம்)', acres: 18, landDetails: 'Turmeric Cultivation (மஞ்சள் சாகுபடி)', workerExpectations: 'Operating tiller and other farm machinery (டில்லர் மற்றும் பிற பண்ணை இயந்திரங்களை இயக்குதல்)', workHours: '8 Hours (8 மணி நேரம்)', salary: 850, farmerEmail: 'nallasivam.attur@email.com', farmerPhone: '9776655435', farmerRating: 4.7, farmerImage: 'https://placehold.co/100x100.png?text=ந', farmerImageHint: 'man with machinery' },
  { farmerName: 'Oviya (ஓவியா)', location: 'Attur, Salem (ஆத்தூர், சேலம்)', acres: 10, landDetails: 'Vegetable and Chilli Farm (காய்கறி மற்றும் மிளகாய் பண்ணை)', workerExpectations: 'Picking vegetables and chillies, and packing (காய்கறிகள், மிளகாய் பறித்தல் மற்றும் கட்டுதல்)', workHours: '7 Hours (7 மணி நேரம்)', salary: 650, farmerEmail: 'oviya.attur@email.com', farmerPhone: '9776655434', farmerRating: 4.9, farmerImage: 'https://placehold.co/100x100.png?text=ஓ', farmerImageHint: 'woman with basket of vegetables' },
  
  // Erode
  { farmerName: 'Manjal Raja (மஞ்சள் ராஜா)', location: 'Erode, Erode (ஈரோடு, ஈரோடு)', acres: 18, landDetails: 'Turmeric Fields (மஞ்சள் வயல்கள்)', workerExpectations: 'Turmeric harvesting and boiling (மஞ்சள் அறுவடை மற்றும் வேகவைத்தல்)', workHours: '8 Hours (8 மணி நேரம்)', salary: 750, farmerEmail: 'manjal.raja@email.com', farmerPhone: '9665544332', farmerRating: 4.8, farmerImage: 'https://placehold.co/100x100.png?text=ம', farmerImageHint: 'man with turmeric' },
  { farmerName: 'Gounder (கவுண்டர்)', location: 'Erode, Erode (ஈரோடு, ஈரோடு)', acres: 25, landDetails: 'Sugarcane and Paddy (கரும்பு மற்றும் நெல்)', workerExpectations: 'Managing irrigation systems for both crops (இரு பயிர்களுக்கும் பாசன வசதிகளை நிர்வகித்தல்)', workHours: '8 Hours (8 மணி நேரம்)', salary: 780, farmerEmail: 'gounder.erode@email.com', farmerPhone: '9665544330', farmerRating: 4.7, farmerImage: 'https://placehold.co/100x100.png?text=க', farmerImageHint: 'farmer by canal' },
  { farmerName: 'Ponnamma (பொன்னம்மா)', location: 'Erode, Erode (ஈரோடு, ஈரோடு)', acres: 12, landDetails: 'Poultry Farm (கோழிப் பண்ணை)', workerExpectations: 'Feeding chickens and collecting eggs (கோழிகளுக்கு தீவனம் வைத்தல் மற்றும் முட்டை சேகரித்தல்)', workHours: '7 Hours (7 மணி நேரம்)', salary: 600, farmerEmail: 'ponnamma.erode@email.com', farmerPhone: '9665544329', farmerRating: 4.6, farmerImage: 'https://placehold.co/100x100.png?text=பொ', farmerImageHint: 'woman with eggs' },
  { farmerName: 'Sakthivel (சக்திவேல்)', location: 'Erode, Erode (ஈரோடு, ஈரோடு)', acres: 22, landDetails: 'Coconut Grove (தென்னந்தோப்பு)', workerExpectations: 'Harvesting coconuts and making copra (தேங்காய் பறித்தல் மற்றும் கொப்பரை தயாரித்தல்)', workHours: '9 Hours (9 மணி நேரம்)', salary: 900, farmerEmail: 'sakthivel.erode@email.com', farmerPhone: '9665544328', farmerRating: 4.8, farmerImage: 'https://placehold.co/100x100.png?text=ச', farmerImageHint: 'man with coconuts' },
  { farmerName: 'Thilaga (திலகா)', location: 'Erode, Erode (ஈரோடு, ஈரோடு)', acres: 8, landDetails: 'Vegetable Farm (காய்கறி பண்ணை)', workerExpectations: 'Organic farming, preparing bio-fertilizers (இயற்கை விவசாயம், உயிர் உரங்கள் தயாரித்தல்)', workHours: '7 Hours (7 மணி நேரம்)', salary: 680, farmerEmail: 'thilaga.erode@email.com', farmerPhone: '9665544327', farmerRating: 4.9, farmerImage: 'https://placehold.co/100x100.png?text=தி', farmerImageHint: 'woman with compost' },

  { farmerName: 'Jamakkalam Janaki (ஜமக்காளம் ஜானகி)', location: 'Bhavani, Erode (பவானி, ஈரோடு)', acres: 2, landDetails: 'Textile crops and weaving unit (நெசவுப் பயிர்கள் மற்றும் நெசவு கூடம்)', workerExpectations: 'Managing textile crops and handloom weaving (நெசவுப் பயிர்களை பராமரித்தல் மற்றும் கைத்தறி நெசவு)', workHours: '7 Hours (7 மணி நேரம்)', salary: 650, farmerEmail: 'jamakkalam.janaki@email.com', farmerPhone: '9665544331', farmerRating: 4.7, farmerImage: 'https://placehold.co/100x100.png?text=ஜா', farmerImageHint: 'woman weaving' },
  { farmerName: 'Kumaravel (குமரவேல்)', location: 'Bhavani, Erode (பவானி, ஈரோடு)', acres: 30, landDetails: 'Paddy and Banana Plantation (நெல் மற்றும் வாழை தோட்டம்)', workerExpectations: 'Operating harvester and managing banana cultivation (அறுவடை இயந்திரம் இயக்குதல் மற்றும் வாழை சாகுபடி மேலாண்மை)', workHours: '9 Hours (9 மணி நேரம்)', salary: 920, farmerEmail: 'kumaravel.bhavani@email.com', farmerPhone: '9665544326', farmerRating: 4.6, farmerImage: 'https://placehold.co/100x100.png?text=கு', farmerImageHint: 'man near harvester' },
  { farmerName: 'Revathi (ரேவதி)', location: 'Bhavani, Erode (பவானி, ஈரோடு)', acres: 10, landDetails: 'Cattle and Dairy Farm (கால்நடை மற்றும் பால் பண்ணை)', workerExpectations: 'Milking cows and preparing dairy products (மாடு பால் கறத்தல் மற்றும் பால் பொருட்கள் தயாரித்தல்)', workHours: '8 Hours (8 மணி நேரம்)', salary: 700, farmerEmail: 'revathi.bhavani@email.com', farmerPhone: '9665544325', farmerRating: 4.8, farmerImage: 'https://placehold.co/100x100.png?text=ரே', farmerImageHint: 'woman with milk cans' },
  { farmerName: 'Subramani (சுப்ரமணி)', location: 'Bhavani, Erode (பவானி, ஈரோடு)', acres: 15, landDetails: 'Fish Farm (மீன் பண்ணை)', workerExpectations: 'Feeding fish and maintaining ponds (மீன்களுக்கு உணவளித்தல் மற்றும் குளங்களை பராமரித்தல்)', workHours: '7 Hours (7 மணி நேரம்)', salary: 670, farmerEmail: 'subramani.bhavani@email.com', farmerPhone: '9665544324', farmerRating: 4.5, farmerImage: 'https://placehold.co/100x100.png?text=சு', farmerImageHint: 'man by a pond' },
  { farmerName: 'Yamuna (யமுனா)', location: 'Bhavani, Erode (பவானி, ஈரோடு)', acres: 5, landDetails: 'Sericulture (பட்டுப்புழு வளர்ப்பு)', workerExpectations: 'Growing mulberry and feeding silkworms (மல்பெரி வளர்த்தல் மற்றும் பட்டுப்புழுக்களுக்கு உணவளித்தல்)', workHours: '8 Hours (8 மணி நேரம்)', salary: 720, farmerEmail: 'yamuna.bhavani@email.com', farmerPhone: '9665544323', farmerRating: 4.9, farmerImage: 'https://placehold.co/100x100.png?text=ய', farmerImageHint: 'woman with silkworms' },

  // Vellore
  { farmerName: 'Rathinam (ரத்தினம்)', location: 'Vellore, Vellore (வேலூர், வேலூர்)', acres: 20, landDetails: 'Paddy and Groundnut fields (நெல் மற்றும் நிலக்கடலை வயல்கள்)', workerExpectations: 'General farm work for paddy and groundnut (நெல், நிலக்கடலை சாகுபடிக்கு பொது பண்ணை வேலை)', workHours: '8 Hours (8 மணி நேரம்)', salary: 680, farmerEmail: 'rathinam.vellore@email.com', farmerPhone: '9554433221', farmerRating: 4.5, farmerImage: 'https://placehold.co/100x100.png?text=ர', farmerImageHint: 'farmer in field' },
  { farmerName: 'Durai (துரை)', location: 'Vellore, Vellore (வேலூர், வேலூர்)', acres: 10, landDetails: 'Mango and Guava Orchard (மா மற்றும் கொய்யா தோட்டம்)', workerExpectations: 'Fruit picking, pruning, and pest control (பழம் பறித்தல், கவாத்து செய்தல், பூச்சி கட்டுப்பாடு)', workHours: '8 Hours (8 மணி நேரம்)', salary: 700, farmerEmail: 'durai.vellore@email.com', farmerPhone: '9554433219', farmerRating: 4.6, farmerImage: 'https://placehold.co/100x100.png?text=து', farmerImageHint: 'farmer in orchard' },
  { farmerName: 'Indrani (இந்திராணி)', location: 'Vellore, Vellore (வேலூர், வேலூர்)', acres: 7, landDetails: 'Brinjal and Tomato Farm (கத்தரி மற்றும் தக்காளி பண்ணை)', workerExpectations: 'Staking plants, harvesting, and sorting vegetables (செடிகளுக்கு முட்டுக்கொடுத்தல், அறுவடை, தரம் பிரித்தல்)', workHours: '7 Hours (7 மணி நேரம்)', salary: 630, farmerEmail: 'indrani.vellore@email.com', farmerPhone: '9554433218', farmerRating: 4.7, farmerImage: 'https://placehold.co/100x100.png?text=இ', farmerImageHint: 'woman with tomatoes' },
  { farmerName: 'Prakash (பிரகாஷ்)', location: 'Vellore, Vellore (வேலூர், வேலூர்)', acres: 15, landDetails: 'Jasmine Flower Cultivation (மல்லிகை பூ சாகுபடி)', workerExpectations: 'Watering, fertilizing, and plucking flowers (நீர்ப்பாசனம், உரமிடுதல், பூ பறித்தல்)', workHours: '6 Hours (6 மணி நேரம்)', salary: 580, farmerEmail: 'prakash.vellore@email.com', farmerPhone: '9554433217', farmerRating: 4.8, farmerImage: 'https://placehold.co/100x100.png?text=பி', farmerImageHint: 'man with jasmine' },
  { farmerName: 'Selvi (செல்வி)', location: 'Vellore, Vellore (வேலூர், வேலூர்)', acres: 12, landDetails: 'Sugarcane Plantation (கரும்பு தோட்டம்)', workerExpectations: 'Weeding and de-trashing sugarcane (களையெடுத்தல் மற்றும் கரும்பு சோகை உரித்தல்)', workHours: '8 Hours (8 மணி நேரம்)', salary: 800, farmerEmail: 'selvi.vellore@email.com', farmerPhone: '9554433216', farmerRating: 4.5, farmerImage: 'https://placehold.co/100x100.png?text=செ', farmerImageHint: 'woman in sugarcane field' },

  { farmerName: 'Basha Bhai (பாஷா பாய்)', location: 'Ambur, Vellore (ஆம்பூர், வேலூர்)', acres: 5, landDetails: 'Land for Seeraga Samba rice (சீரக சம்பா அரிசிக்கு நிலம்)', workerExpectations: 'Cultivate Seeraga Samba rice for Biryani (பிரியாணிக்கு சீரக சம்பா அரிசி சாகுபடி)', workHours: '8 Hours (8 மணி நேரம்)', salary: 720, farmerEmail: 'basha.ambur@email.com', farmerPhone: '9554433220', farmerRating: 4.8, farmerImage: 'https://placehold.co/100x100.png?text=பா', farmerImageHint: 'man in rice paddy' },
  { farmerName: 'Jabbar (ஜப்பார்)', location: 'Ambur, Vellore (ஆம்பூர், வேலூர்)', acres: 3, landDetails: 'Goat and Sheep Farm (ஆடு மற்றும் செம்மறிப் பண்ணை)', workerExpectations: 'Grazing and caring for livestock (கால்நடைகளை மேய்த்தல் மற்றும் பராமரித்தல்)', workHours: '9 Hours (9 மணி நேரம்)', salary: 750, farmerEmail: 'jabbar.ambur@email.com', farmerPhone: '9554433215', farmerRating: 4.6, farmerImage: 'https://placehold.co/100x100.png?text=ஜ', farmerImageHint: 'man with goats' },
  { farmerName: 'Raziya (ரஜியா)', location: 'Ambur, Vellore (ஆம்பூர், வேலூர்)', acres: 2, landDetails: 'Home garden for vegetables (வீட்டுத் தேவைக்கு காய்கறி தோட்டம்)', workerExpectations: 'Growing organic vegetables for home and local sale (வீட்டு உபயோகம் மற்றும் உள்ளூர் விற்பனைக்கு காய்கறி பயிரிடுதல்)', workHours: '5 Hours (5 மணி நேரம்)', salary: 500, farmerEmail: 'raziya.ambur@email.com', farmerPhone: '9554433214', farmerRating: 4.9, farmerImage: 'https://placehold.co/100x100.png?text=ர', farmerImageHint: 'woman gardening' },
  { farmerName: 'Khader (காதர்)', location: 'Ambur, Vellore (ஆம்பூர், வேலூர்)', acres: 8, landDetails: 'Groundnut and Millets (நிலக்கடலை மற்றும் சிறுதானியங்கள்)', workerExpectations: 'Driving tractor and managing farm operations (டிராக்டர் ஓட்டுதல் மற்றும் பண்ணை பணிகளை நிர்வகித்தல்)', workHours: '8 Hours (8 மணி நேரம்)', salary: 850, farmerEmail: 'khader.ambur@email.com', farmerPhone: '9554433213', farmerRating: 4.7, farmerImage: 'https://placehold.co/100x100.png?text=கா', farmerImageHint: 'man on tractor' },
  { farmerName: 'Yasmin (யாஸ்மின்)', location: 'Ambur, Vellore (ஆம்பூர், வேலூர்)', acres: 4, landDetails: 'Tannery effluent treatment plant nursery (தோல் கழிவு நீர் சுத்திகரிப்பு நிலைய நாற்றங்கால்)', workerExpectations: 'Growing plants that help in water purification (நீர் சுத்திகரிப்புக்கு உதவும் செடிகளை வளர்த்தல்)', workHours: '7 Hours (7 மணி நேரம்)', salary: 680, farmerEmail: 'yasmin.ambur@email.com', farmerPhone: '9554433212', farmerRating: 4.8, farmerImage: 'https://placehold.co/100x100.png?text=யா', farmerImageHint: 'woman with plants' },

  // Tirunelveli
  { farmerName: 'Nellai Appan (நெல்லையப்பன்)', location: 'Tirunelveli, Tirunelveli (திருநெல்வேலி, திருநெல்வேலி)', acres: 30, landDetails: 'Paddy, Banana, and Palm trees (நெல், வாழை, பனை மரங்கள்)', workerExpectations: 'Harvesting paddy, managing bananas, and climbing palm trees (நெல் அறுவடை, வாழை பராமரிப்பு, பனை மரம் ஏறுதல்)', workHours: '9 Hours (9 மணி நேரம்)', salary: 880, farmerEmail: 'nellai.appan@email.com', farmerPhone: '9443322110', farmerRating: 4.9, farmerImage: 'https://placehold.co/100x100.png?text=நெ', farmerImageHint: 'older farmer' },
  { farmerName: 'Sudalai (சுடலை)', location: 'Tirunelveli, Tirunelveli (திருநெல்வேலி, திருநெல்வேலி)', acres: 15, landDetails: 'Chilli and Cotton Fields (மிளகாய் மற்றும் பருத்தி காடு)', workerExpectations: 'Picking chillies and cotton (மிளகாய் வற்றல் மற்றும் பருத்தி எடுத்தல்)', workHours: '8 Hours (8 மணி நேரம்)', salary: 700, farmerEmail: 'sudalai.tirunelveli@email.com', farmerPhone: '9443322108', farmerRating: 4.6, farmerImage: 'https://placehold.co/100x100.png?text=சு', farmerImageHint: 'farmer in chilli field' },
  { farmerName: 'Gomathi (கோமதி)', location: 'Tirunelveli, Tirunelveli (திருநெல்வேலி, திருநெல்வேலி)', acres: 10, landDetails: 'Vegetable Farm near river (ஆற்றங்கரை காய்கறி தோட்டம்)', workerExpectations: 'Irrigating from river and harvesting vegetables (ஆற்றிலிருந்து நீர் பாய்ச்சி காய்கறி அறுவடை செய்தல்)', workHours: '7 Hours (7 மணி நேரம்)', salary: 650, farmerEmail: 'gomathi.tirunelveli@email.com', farmerPhone: '9443322107', farmerRating: 4.8, farmerImage: 'https://placehold.co/100x100.png?text=கோ', farmerImageHint: 'woman by a river' },
  { farmerName: 'Sivan (சிவன்)', location: 'Tirunelveli, Tirunelveli (திருநெல்வேலி, திருநெல்வேலி)', acres: 25, landDetails: 'Livestock Farm (கால்நடைப் பண்ணை)', workerExpectations: 'Managing cattle, goats, and poultry (மாடு, ஆடு, கோழிகளைப் பராமரித்தல்)', workHours: '9 Hours (9 மணி நேரம்)', salary: 850, farmerEmail: 'sivan.tirunelveli@email.com', farmerPhone: '9443322106', farmerRating: 4.7, farmerImage: 'https://placehold.co/100x100.png?text=சி', farmerImageHint: 'man with livestock' },
  { farmerName: 'Halwa Hameed (அல்வா ஹமீது)', location: 'Tirunelveli, Tirunelveli (திருநெல்வேலி, திருநெல்வேலி)', acres: 1, landDetails: 'Land for wheat cultivation (கோதுமை சாகுபடிக்கு நிலம்)', workerExpectations: 'Cultivate wheat for making Halwa (அல்வா தயாரிக்க கோதுமை சாகுபடி)', workHours: '7 Hours (7 மணி நேரம்)', salary: 600, farmerEmail: 'halwa.hameed@email.com', farmerPhone: '9443322119', farmerRating: 4.7, farmerImage: 'https://placehold.co/100x100.png?text=அ', farmerImageHint: 'man smiling' },

  // Thanjavur
  { farmerName: 'Ponni Selvan (பொன்னி செல்வன்)', location: 'Thanjavur, Thanjavur (தஞ்சாவூர், தஞ்சாவூர்)', acres: 50, landDetails: 'Paddy fields (Delta region) (நெல் வயல்கள் (டெல்டா பகுதி))', workerExpectations: 'Complete paddy cultivation cycle work (முழு நெல் சாகுபடி சுழற்சி வேலை)', workHours: '8 Hours (8 மணி நேரம்)', salary: 750, farmerEmail: 'ponni.selvan@email.com', farmerPhone: '9332211009', farmerRating: 5.0, farmerImage: 'https://placehold.co/100x100.png?text=பொ', farmerImageHint: 'farmer in paddy' },
  { farmerName: 'Karikalan (கரிகாலன்)', location: 'Thanjavur, Thanjavur (தஞ்சாவூர், தஞ்சாவூர்)', acres: 30, landDetails: 'Coconut and Banana (தென்னை மற்றும் வாழை)', workerExpectations: 'Intercropping management and harvesting (ஊடுபயிர் மேலாண்மை மற்றும் அறுவடை)', workHours: '8 Hours (8 மணி நேரம்)', salary: 780, farmerEmail: 'karikalan.thanjavur@email.com', farmerPhone: '9332211007', farmerRating: 4.8, farmerImage: 'https://placehold.co/100x100.png?text=க', farmerImageHint: 'farmer in coconut grove' },
  { farmerName: 'Senthamarai (செந்தாமரை)', location: 'Thanjavur, Thanjavur (தஞ்சாவூர், தஞ்சாவூர்)', acres: 10, landDetails: 'Black Gram and Green Gram (உளுந்து மற்றும் பாசிப்பயறு)', workerExpectations: 'Harvesting and threshing pulses (பயறு வகைகளை அறுவடை செய்து போரடித்தல்)', workHours: '7 Hours (7 மணி நேரம்)', salary: 650, farmerEmail: 'senthamarai.thanjavur@email.com', farmerPhone: '9332211006', farmerRating: 4.7, farmerImage: 'https://placehold.co/100x100.png?text=செ', farmerImageHint: 'woman with pulses' },
  { farmerName: 'Valavan (வளவன்)', location: 'Thanjavur, Thanjavur (தஞ்சாவூர், தஞ்சாவூர்)', acres: 40, landDetails: 'Sugarcane Fields (கரும்பு வயல்கள்)', workerExpectations: 'Operating sugarcane harvester machine (கரும்பு அறுவடை இயந்திரம் இயக்குதல்)', workHours: '9 Hours (9 மணி நேரம்)', salary: 950, farmerEmail: 'valavan.thanjavur@email.com', farmerPhone: '9332211005', farmerRating: 4.9, farmerImage: 'https://placehold.co/100x100.png?text=வ', farmerImageHint: 'man on harvester' },
  { farmerName: 'Manimekalai (மணிமேகலை)', location: 'Thanjavur, Thanjavur (தஞ்சாவூர், தஞ்சாவூர்)', acres: 8, landDetails: 'Sesame Cultivation (எள் சாகுபடி)', workerExpectations: 'Harvesting sesame and oil extraction (எள் அறுவடை மற்றும் எண்ணெய் ஆட்டுதல்)', workHours: '8 Hours (8 மணி நேரம்)', salary: 720, farmerEmail: 'manimekalai.thanjavur@email.com', farmerPhone: '9332211004', farmerRating: 4.6, farmerImage: 'https://placehold.co/100x100.png?text=ம', farmerImageHint: 'woman with sesame seeds' },

  { farmerName: 'Rajarajan (ராஜராஜன்)', location: 'Kumbakonam, Thanjavur (கும்பகோணம், தஞ்சாவூர்)', acres: 10, landDetails: 'Betel leaves and Sugarcane (வெற்றிலை மற்றும் கரும்பு)', workerExpectations: 'Betel leaf plucking and sugarcane harvesting (வெற்றிலை பறித்தல் மற்றும் கரும்பு வெட்டுதல்)', workHours: '7 Hours (7 மணி நேரம்)', salary: 680, farmerEmail: 'rajarajan.kumbakonam@email.com', farmerPhone: '9332211008', farmerRating: 4.7, farmerImage: 'https://placehold.co/100x100.png?text=ரா', farmerImageHint: 'farmer smiling' },
  { farmerName: 'Sivagami (சிவகாமி)', location: 'Kumbakonam, Thanjavur (கும்பகோணம், தஞ்சாவூர்)', acres: 5, landDetails: 'Temple Flower Garden (கோவில் பூந்தோட்டம்)', workerExpectations: 'Cultivating and providing flowers for temples (கோவில்களுக்கு பூக்கள் பயிரிட்டு வழங்குதல்)', workHours: '6 Hours (6 மணி நேரம்)', salary: 580, farmerEmail: 'sivagami.kumbakonam@email.com', farmerPhone: '9332211003', farmerRating: 4.9, farmerImage: 'https://placehold.co/100x100.png?text=சி', farmerImageHint: 'woman with flower basket' },
  { farmerName: 'Nageswaran (நாகேஸ்வரன்)', location: 'Kumbakonam, Thanjavur (கும்பகோணம், தஞ்சாவூர்)', acres: 12, landDetails: 'Paddy and Pulses (நெல் மற்றும் பயறு வகைகள்)', workerExpectations: 'Crop rotation management and general farm work (பயிர் சுழற்சி மேலாண்மை மற்றும் பொது பண்ணை வேலைகள்)', workHours: '8 Hours (8 மணி நேரம்)', salary: 730, farmerEmail: 'nageswaran.kumbakonam@email.com', farmerPhone: '9332211002', farmerRating: 4.6, farmerImage: 'https://placehold.co/100x100.png?text=நா', farmerImageHint: 'farmer in a field' },
  { farmerName: 'Gomathi (கோமதி)', location: 'Kumbakonam, Thanjavur (கும்பகோணம், தஞ்சாவூர்)', acres: 3, landDetails: 'Brass works related material cultivation (பித்தளை வேலைக்குத் தேவையான மூலப்பொருள் சாகுபடி)', workerExpectations: 'Growing plants used for polishing brassware (பித்தளை பாத்திரங்களை பாலிஷ் செய்ய பயன்படும் செடிகளை வளர்த்தல்)', workHours: '7 Hours (7 மணி நேரம்)', salary: 620, farmerEmail: 'gomathi.kumbakonam@email.com', farmerPhone: '9332211001', farmerRating: 4.8, farmerImage: 'https://placehold.co/100x100.png?text=கோ', farmerImageHint: 'woman with plants' },
  { farmerName: 'Adithan (ஆதித்தன்)', location: 'Kumbakonam, Thanjavur (கும்பகோணம், தஞ்சாவூர்)', acres: 20, landDetails: 'Rice Mill and Paddy Storage (அரிசி ஆலை மற்றும் நெல் சேமிப்பு)', workerExpectations: 'Managing mill operations and paddy logistics (அரிசி ஆலை மற்றும் நெல் வரத்து நிர்வாகம்)', workHours: '9 Hours (9 மணி நேரம்)', salary: 900, farmerEmail: 'adithan.kumbakonam@email.com', farmerPhone: '9332211000', farmerRating: 4.7, farmerImage: 'https://placehold.co/100x100.png?text=ஆ', farmerImageHint: 'man in a rice mill' },

  // Dindigul
  { farmerName: 'Poottu Muthu (பூட்டு முத்து)', location: 'Dindigul, Dindigul (திண்டுக்கல், திண்டுக்கல்)', acres: 3, landDetails: 'Land for metal work raw materials (உலோக வேலை மூலப்பொருட்களுக்கான நிலம்)', workerExpectations: 'Cultivate plants for lock making dye/materials (பூட்டுக்கு சாயம்/மூலப்பொருட்களுக்கு செடிகள் வளர்த்தல்)', workHours: '8 Hours (8 மணி நேரம்)', salary: 650, farmerEmail: 'poottu.muthu@email.com', farmerPhone: '9221100998', farmerRating: 4.6, farmerImage: 'https://placehold.co/100x100.png?text=பூ', farmerImageHint: 'man in workshop' },
  { farmerName: 'Biryani Begum (பிரியாணி பேகம்)', location: 'Dindigul, Dindigul (திண்டுக்கல், திண்டுக்கல்)', acres: 6, landDetails: 'Seeraga Samba Rice fields (சீரக சம்பா நெல் வயல்கள்)', workerExpectations: 'Cultivate and harvest Seeraga Samba rice (சீரக சம்பா நெல் சாகுபடி மற்றும் அறுவடை)', workHours: '8 Hours (8 மணி நேரம்)', salary: 730, farmerEmail: 'biryani.begum@email.com', farmerPhone: '9221100997', farmerRating: 4.8, farmerImage: 'https://placehold.co/100x100.png?text=பி', farmerImageHint: 'woman in rice field' },
  { farmerName: 'Ganesan (கணேசன்)', location: 'Dindigul, Dindigul (திண்டுக்கல், திண்டுக்கல்)', acres: 15, landDetails: 'Grape Vines (திராட்சை தோட்டம்)', workerExpectations: 'Pruning grape vines and harvesting grapes (திராட்சை செடிகளை கவாத்து செய்தல் மற்றும் பழம் பறித்தல்)', workHours: '7 Hours (7 மணி நேரம்)', salary: 700, farmerEmail: 'ganesan.dindigul@email.com', farmerPhone: '9221100996', farmerRating: 4.7, farmerImage: 'https://placehold.co/100x100.png?text=க', farmerImageHint: 'man in vineyard' },
  { farmerName: 'Kala (கலா)', location: 'Dindigul, Dindigul (திண்டுக்கல், திண்டுக்கல்)', acres: 10, landDetails: 'Moringa and Papaya Farm (முருங்கை மற்றும் பப்பாளி பண்ணை)', workerExpectations: 'Harvesting moringa pods and papayas (முருங்கைக்காய் மற்றும் பப்பாளி அறுவடை)', workHours: '7 Hours (7 மணி நேரம்)', salary: 640, farmerEmail: 'kala.dindigul@email.com', farmerPhone: '9221100995', farmerRating: 4.9, farmerImage: 'https://placehold.co/100x100.png?text=க', farmerImageHint: 'woman with moringa' },
  { farmerName: 'Velmurugan (வேல்முருகன்)', location: 'Dindigul, Dindigul (திண்டுக்கல், திண்டுக்கல்)', acres: 20, landDetails: 'Guava and Amla Orchard (கொய்யா மற்றும் நெல்லி தோட்டம்)', workerExpectations: 'Driving a mini truck for transport to market (சந்தைக்கு கொண்டு செல்ல மினி டிரக் ஓட்டுதல்)', workHours: '8 Hours (8 மணி நேரம்)', salary: 800, farmerEmail: 'velmurugan.dindigul@email.com', farmerPhone: '9221100994', farmerRating: 4.5, farmerImage: 'https://placehold.co/100x100.png?text=வே', farmerImageHint: 'man with truck' },

  // Kanyakumari
  { farmerName: 'Rubber Rajan (ரப்பர் ராஜன்)', location: 'Nagercoil, Kanyakumari (நாகர்கோவில், கன்னியாகுமரி)', acres: 20, landDetails: 'Rubber Plantation (ரப்பர் தோட்டம்)', workerExpectations: 'Rubber tapping and sheet processing (ரப்பர் பால் வெட்டுதல் மற்றும் ஷீட் தயாரித்தல்)', workHours: '7 Hours (7 மணி நேரம்)', salary: 820, farmerEmail: 'rubber.rajan@email.com', farmerPhone: '9110099887', farmerRating: 4.7, farmerImage: 'https://placehold.co/100x100.png?text=ர', farmerImageHint: 'man tapping rubber' },
  { farmerName: 'Mary (மேரி)', location: 'Nagercoil, Kanyakumari (நாகர்கோவில், கன்னியாகுமரி)', acres: 5, landDetails: 'Fishing and Coconut Grove (மீன்பிடி மற்றும் தென்னந்தோப்பு)', workerExpectations: 'Managing coastal farm and fishing activities (கடலோர பண்ணை மற்றும் மீன்பிடி வேலைகளை நிர்வகித்தல்)', workHours: '8 Hours (8 மணி நேரம்)', salary: 750, farmerEmail: 'mary.nagercoil@email.com', farmerPhone: '9110099885', farmerRating: 4.8, farmerImage: 'https://placehold.co/100x100.png?text=மே', farmerImageHint: 'woman near fishing boats' },
  { farmerName: 'David (டேவிட்)', location: 'Nagercoil, Kanyakumari (நாகர்கோவில், கன்னியாகுமரி)', acres: 10, landDetails: 'Tapioca and Banana Farm (மரவள்ளி மற்றும் வாழை பண்ணை)', workerExpectations: 'Harvesting tapioca and banana bunches (மரவள்ளி மற்றும் வாழைத்தார் அறுவடை)', workHours: '8 Hours (8 மணி நேரம்)', salary: 700, farmerEmail: 'david.nagercoil@email.com', farmerPhone: '9110099884', farmerRating: 4.6, farmerImage: 'https://placehold.co/100x100.png?text=டே', farmerImageHint: 'farmer with tapioca' },
  { farmerName: 'Pushpa (புஷ்பா)', location: 'Nagercoil, Kanyakumari (நாகர்கோவில், கன்னியாகுமரி)', acres: 3, landDetails: 'Flower garden for garlands (மாலைகளுக்கான பூந்தோட்டம்)', workerExpectations: 'Cultivating various flowers and making garlands (பலவகை பூக்கள் பயிரிட்டு மாலை கட்டுதல்)', workHours: '6 Hours (6 மணி நேரம்)', salary: 550, farmerEmail: 'pushpa.nagercoil@email.com', farmerPhone: '9110099883', farmerRating: 4.9, farmerImage: 'https://placehold.co/100x100.png?text=பு', farmerImageHint: 'woman stringing flowers' },
  { farmerName: 'Wilson (வில்சன்)', location: 'Nagercoil, Kanyakumari (நாகர்கோவில், கன்னியாகுமரி)', acres: 12, landDetails: 'Paddy Fields (நெல் வயல்கள்)', workerExpectations: 'Land preparation and pesticide spraying (நிலத்தை தயார் செய்தல் மற்றும் பூச்சிமருந்து அடித்தல்)', workHours: '8 Hours (8 மணி நேரம்)', salary: 780, farmerEmail: 'wilson.nagercoil@email.com', farmerPhone: '9110099882', farmerRating: 4.5, farmerImage: 'https://placehold.co/100x100.png?text=வி', farmerImageHint: 'farmer spraying pesticides' },

  { farmerName: 'Nanjil Nambi (நாஞ்சில் நம்பி)', location: 'Thuckalay, Kanyakumari (தக்கலை, கன்னியாகுமரி)', acres: 12, landDetails: 'Cloves and Nutmeg plantation (கிராம்பு, ஜாதிக்காய் தோட்டம்)', workerExpectations: 'Spice harvesting and drying (நறுமணப் பொருட்கள் அறுவடை மற்றும் உலர்த்துதல்)', workHours: '7 Hours (7 மணி நேரம்)', salary: 750, farmerEmail: 'nanjil.nambi@email.com', farmerPhone: '9110099886', farmerRating: 4.9, farmerImage: 'https://placehold.co/100x100.png?text=நா', farmerImageHint: 'farmer with spices' },
  { farmerName: 'George (ஜார்ஜ்)', location: 'Thuckalay, Kanyakumari (தக்கலை, கன்னியாகுமரி)', acres: 15, landDetails: 'Rubber and Pepper Plantation (ரப்பர் மற்றும் மிளகு தோட்டம்)', workerExpectations: 'Tapping rubber and harvesting pepper vines (ரப்பர் பால் வெட்டுதல் மற்றும் மிளகு கொடிகளை அறுவடை செய்தல்)', workHours: '8 Hours (8 மணி நேரம்)', salary: 850, farmerEmail: 'george.thuckalay@email.com', farmerPhone: '9110099881', farmerRating: 4.7, farmerImage: 'https://placehold.co/100x100.png?text=ஜா', farmerImageHint: 'man with pepper vines' },
  { farmerName: 'Stella (ஸ்டெல்லா)', location: 'Thuckalay, Kanyakumari (தக்கலை, கன்னியாகுமரி)', acres: 8, landDetails: 'Cashew Farm (முந்திரி பண்ணை)', workerExpectations: 'Harvesting and processing cashew apples and nuts (முந்திரி பழம் மற்றும் கொட்டை அறுவடை செய்து பதப்படுத்துதல்)', workHours: '8 Hours (8 மணி நேரம்)', salary: 720, farmerEmail: 'stella.thuckalay@email.com', farmerPhone: '9110099880', farmerRating: 4.8, farmerImage: 'https://placehold.co/100x100.png?text=ஸ்', farmerImageHint: 'woman with cashews' },
  { farmerName: 'Arul (அருள்)', location: 'Thuckalay, Kanyakumari (தக்கலை, கன்னியாகுமரி)', acres: 10, landDetails: 'Pineapple Plantation (அன்னாசி தோட்டம்)', workerExpectations: 'Planting pineapple crowns and harvesting fruits (அன்னாசி செடிகளை நட்டு, பழங்களை அறுவடை செய்தல்)', workHours: '7 Hours (7 மணி நேரம்)', salary: 680, farmerEmail: 'arul.thuckalay@email.com', farmerPhone: '9110099879', farmerRating: 4.6, farmerImage: 'https://placehold.co/100x100.png?text=அ', farmerImageHint: 'farmer with pineapple' },
  { farmerName: 'Theresa (தெரசா)', location: 'Thuckalay, Kanyakumari (தக்கலை, கன்னியாகுமரி)', acres: 5, landDetails: 'Mixed Fruit Orchard (பழப்பண்ணை)', workerExpectations: 'Maintaining various fruit trees and general farm work (பல்வேறு பழ மரங்களை பராமரித்தல் மற்றும் பொது பண்ணை வேலைகள்)', workHours: '7 Hours (7 மணி நேரம்)', salary: 650, farmerEmail: 'theresa.thuckalay@email.com', farmerPhone: '9110099878', farmerRating: 4.9, farmerImage: 'https://placehold.co/100x100.png?text=தெ', farmerImageHint: 'woman in an orchard' },
  
  // Tiruppur
  { farmerName: 'Baniyan Baskar (பனியன் பாஸ்கர்)', location: 'Tiruppur, Tiruppur (திருப்பூர், திருப்பூர்)', acres: 10, landDetails: 'Cotton Fields (பருத்தி காடு)', workerExpectations: 'Cotton picking for garment industry (ஆயத்த ஆடை தொழிலுக்கு பருத்தி எடுத்தல்)', workHours: '8 Hours (8 மணி நேரம்)', salary: 700, farmerEmail: 'banian.baskar@email.com', farmerPhone: '9009988776', farmerRating: 4.6, farmerImage: 'https://placehold.co/100x100.png?text=ப', farmerImageHint: 'man in cotton field' },
  { farmerName: 'Saminathan (சாமிநாதன்)', location: 'Tiruppur, Tiruppur (திருப்பூர், திருப்பூர்)', acres: 20, landDetails: 'Maize and Sunflower Farm (மக்காச்சோளம் மற்றும் சூரியகாந்தி பண்ணை)', workerExpectations: 'Operating farm machinery for sowing and harvesting (விதைப்பு மற்றும் அறுவடைக்கு பண்ணை இயந்திரங்களை இயக்குதல்)', workHours: '9 Hours (9 மணி நேரம்)', salary: 900, farmerEmail: 'saminathan.tiruppur@email.com', farmerPhone: '9009988774', farmerRating: 4.7, farmerImage: 'https://placehold.co/100x100.png?text=சா', farmerImageHint: 'man on a tractor' },
  { farmerName: 'Kokila (கோகிலா)', location: 'Tiruppur, Tiruppur (திருப்பூர், திருப்பூர்)', acres: 8, landDetails: 'Guava Orchard (கொய்யா தோட்டம்)', workerExpectations: 'Plucking, grading, and packing guavas (கொய்யா பறித்தல், தரம் பிரித்தல், மற்றும் கட்டுதல்)', workHours: '7 Hours (7 மணி நேரம்)', salary: 650, farmerEmail: 'kokila.tiruppur@email.com', farmerPhone: '9009988773', farmerRating: 4.8, farmerImage: 'https://placehold.co/100x100.png?text=கோ', farmerImageHint: 'woman with guavas' },
  { farmerName: 'Rangasamy (ரங்கசாமி)', location: 'Tiruppur, Tiruppur (திருப்பூர், திருப்பூர்)', acres: 15, landDetails: 'Vegetable Farm with Drip Irrigation (சொட்டு நீர் பாசன காய்கறி பண்ணை)', workerExpectations: 'Maintaining drip irrigation system and vegetable cultivation (சொட்டு நீர் பாசன முறையை பராமரித்தல் மற்றும் காய்கறி சாகுபடி)', workHours: '8 Hours (8 மணி நேரம்)', salary: 720, farmerEmail: 'rangasamy.tiruppur@email.com', farmerPhone: '9009988772', farmerRating: 4.9, farmerImage: 'https://placehold.co/100x100.png?text=ர', farmerImageHint: 'farmer with drip irrigation' },
  { farmerName: 'Malar (மலர்)', location: 'Tiruppur, Tiruppur (திருப்பூர், திருப்பூர்)', acres: 5, landDetails: 'Land for growing dye plants (சாயச் செடிகள் வளர்க்கும் நிலம்)', workerExpectations: 'Growing plants for natural dyes for textile units (ஆடை நிறுவனங்களுக்கு இயற்கை சாயம் தயாரிக்க செடிகள் வளர்த்தல்)', workHours: '7 Hours (7 மணி நேரம்)', salary: 680, farmerEmail: 'malar.tiruppur@email.com', farmerPhone: '9009988771', farmerRating: 4.7, farmerImage: 'https://placehold.co/100x100.png?text=ம', farmerImageHint: 'woman with colorful plants' },

  { farmerName: 'Knit Kavitha (நிட் கவிதா)', location: 'Avinashi, Tiruppur (அவினாசி, திருப்பூர்)', acres: 5, landDetails: 'Land for organic cotton dye plants (ஆர்கானிக் காட்டன் சாயச் செடிகள்)', workerExpectations: 'Cultivate plants for making natural dyes (இயற்கை சாயம் தயாரிக்க செடிகள் வளர்த்தல்)', workHours: '7 Hours (7 மணி நேரம்)', salary: 650, farmerEmail: 'knit.kavitha@email.com', farmerPhone: '9009988775', farmerRating: 4.8, farmerImage: 'https://placehold.co/100x100.png?text=நி', farmerImageHint: 'woman with plants' },
  { farmerName: 'Palanisamy (பழனிசாமி)', location: 'Avinashi, Tiruppur (அவினாசி, திருப்பூர்)', acres: 25, landDetails: 'Coconut and Fodder Grass (தென்னை மற்றும் தீவனப் புல்)', workerExpectations: 'Managing integrated farm with livestock (கால்நடைகளுடன் கூடிய ஒருங்கிணைந்த பண்ணையை நிர்வகித்தல்)', workHours: '9 Hours (9 மணி நேரம்)', salary: 880, farmerEmail: 'palanisamy.avinashi@email.com', farmerPhone: '9009988770', farmerRating: 4.6, farmerImage: 'https://placehold.co/100x100.png?text=ப', farmerImageHint: 'farmer with cows' },
  { farmerName: 'Jothi (ஜோதி)', location: 'Avinashi, Tiruppur (அவினாசி, திருப்பூர்)', acres: 10, landDetails: 'Small Onion (Shallots) Farm (சின்ன வெங்காயம் பண்ணை)', workerExpectations: 'Harvesting, curing, and grading onions (வெங்காயம் அறுவடை, பதப்படுத்துதல், தரம் பிரித்தல்)', workHours: '8 Hours (8 மணி நேரம்)', salary: 700, farmerEmail: 'jothi.avinashi@email.com', farmerPhone: '9009988769', farmerRating: 4.7, farmerImage: 'https://placehold.co/100x100.png?text=ஜோ', farmerImageHint: 'woman with onions' },
  { farmerName: 'Velusamy (வேலுசாமி)', location: 'Avinashi, Tiruppur (அவினாசி, திருப்பூர்)', acres: 18, landDetails: 'Windmill Farm with Sheep grazing (காற்றாலை மற்றும் செம்மறி மேய்ச்சல் நிலம்)', workerExpectations: 'Herding sheep and general maintenance of windmill area (செம்மறி ஆடுகளை மேய்த்தல் மற்றும் காற்றாலை பகுதியை பராமரித்தல்)', workHours: '8 Hours (8 மணி நேரம்)', salary: 750, farmerEmail: 'velusamy.avinashi@email.com', farmerPhone: '9009988768', farmerRating: 4.5, farmerImage: 'https://placehold.co/100x100.png?text=வே', farmerImageHint: 'man with sheep and windmills' },
  { farmerName: 'Anitha (அனிதா)', location: 'Avinashi, Tiruppur (அவினாசி, திருப்பூர்)', acres: 7, landDetails: 'Vegetable farm supplying to garment canteens (ஆடை நிறுவன உணவகங்களுக்கு காய்கறி பண்ணை)', workerExpectations: 'Growing and supplying fresh vegetables daily (தினமும் તાજા காய்கறிகளை வளர்த்து வழங்குதல்)', workHours: '7 Hours (7 மணி நேரம்)', salary: 660, farmerEmail: 'anitha.avinashi@email.com', farmerPhone: '9009988767', farmerRating: 4.9, farmerImage: 'https://placehold.co/100x100.png?text=அ', farmerImageHint: 'woman delivering vegetables' },

  // Karur
  { farmerName: 'Mosquito Net Murugan (கொசுவலை முருகன்)', location: 'Karur, Karur (கரூர், கரூர்)', acres: 7, landDetails: 'Agave and other fiber crops (கற்றாழை மற்றும் மற்ற நார் பயிர்கள்)', workerExpectations: 'Harvest fibers for net making (வலை பின்ன நார் அறுவடை செய்தல்)', workHours: '8 Hours (8 மணி நேரம்)', salary: 680, farmerEmail: 'net.murugan@email.com', farmerPhone: '8998877665', farmerRating: 4.5, farmerImage: 'https://placehold.co/100x100.png?text=கொ', farmerImageHint: 'farmer with fibers' },
  { farmerName: 'Chellappan (செல்லப்பன்)', location: 'Karur, Karur (கரூர், கரூர்)', acres: 10, landDetails: 'Drumstick Plantation (முருங்கை தோட்டம்)', workerExpectations: 'Harvesting drumsticks and packing for export (முருங்கைக்காய் அறுவடை செய்து ஏற்றுமதிக்கு கட்டுதல்)', workHours: '8 Hours (8 மணி நேரம்)', salary: 720, farmerEmail: 'chellappan.karur@email.com', farmerPhone: '8998877663', farmerRating: 4.7, farmerImage: 'https://placehold.co/100x100.png?text=செ', farmerImageHint: 'man with drumsticks' },
  { farmerName: 'Parvathi (பார்வதி)', location: 'Karur, Karur (கரூர், கரூர்)', acres: 5, landDetails: 'Home textiles related crop cultivation ( வீட்டு உபயோக ஜவுளி பயிர் சாகுபடி)', workerExpectations: 'Cultivating cotton and other natural fibers for textiles (ஜவுளிக்காக பருத்தி மற்றும் இயற்கை நார்களை பயிரிடுதல்)', workHours: '7 Hours (7 மணி நேரம்)', salary: 650, farmerEmail: 'parvathi.karur@email.com', farmerPhone: '8998877662', farmerRating: 4.8, farmerImage: 'https://placehold.co/100x100.png?text=பா', farmerImageHint: 'woman with cotton' },
  { farmerName: 'Kaliappan (காளியப்பன்)', location: 'Karur, Karur (கரூர், கரூர்)', acres: 12, landDetails: 'Paper mill related wood plantation (காகித ஆலைக்கான மரங்கள் தோட்டம்)', workerExpectations: 'Planting and cutting trees for paper pulp (காகித கூழ் தயாரிக்க மரம் நடுதல் மற்றும் வெட்டுதல்)', workHours: '9 Hours (9 மணி நேரம்)', salary: 850, farmerEmail: 'kaliappan.karur@email.com', farmerPhone: '8998877661', farmerRating: 4.6, farmerImage: 'https://placehold.co/100x100.png?text=கா', farmerImageHint: 'man cutting wood' },
  { farmerName: 'Lakshmi (லட்சுமி)', location: 'Karur, Karur (கரூர், கரூர்)', acres: 8, landDetails: 'Papaya Farm (பப்பாளி பண்ணை)', workerExpectations: 'Harvesting papaya and extracting papain enzyme (பப்பாளி அறுவடை மற்றும் பப்பெய்ன் என்சைம் பிரித்தெடுத்தல்)', workHours: '8 Hours (8 மணி நேரம்)', salary: 700, farmerEmail: 'lakshmi.karur@email.com', farmerPhone: '8998877660', farmerRating: 4.9, farmerImage: 'https://placehold.co/100x100.png?text=ல', farmerImageHint: 'woman with papayas' },

  { farmerName: 'Vasanthi (வாசந்தி)', location: 'Kulithalai, Karur (குளித்தலை, கரூர்)', acres: 15, landDetails: 'Betel leaf and Banana plantation (வெற்றிலை மற்றும் வாழை தோட்டம்)', workerExpectations: 'Harvesting betel leaves and bananas (வெற்றிலை மற்றும் வாழை அறுவடை)', workHours: '7 Hours (7 மணி நேரம்)', salary: 650, farmerEmail: 'vasanthi.k@email.com', farmerPhone: '8998877664', farmerRating: 4.7, farmerImage: 'https://placehold.co/100x100.png?text=வா', farmerImageHint: 'woman in plantation' },
  { farmerName: 'Rajendran (ராஜேந்திரன்)', location: 'Kulithalai, Karur (குளித்தலை, கரூர்)', acres: 20, landDetails: 'Paddy and Sugarcane Fields (நெல் மற்றும் கரும்பு வயல்கள்)', workerExpectations: 'Water management from Cauvery river and harvesting (காவிரி ஆற்று நீர் மேலாண்மை மற்றும் அறுவடை)', workHours: '8 Hours (8 மணி நேரம்)', salary: 780, farmerEmail: 'rajendran.kulithalai@email.com', farmerPhone: '8998877659', farmerRating: 4.6, farmerImage: 'https://placehold.co/100x100.png?text=ரா', farmerImageHint: 'farmer near a river' },
  { farmerName: 'Manonmani (மனோன்மணி)', location: 'Kulithalai, Karur (குளித்தலை, கரூர்)', acres: 10, landDetails: 'Groundnut farm (நிலக்கடலை பண்ணை)', workerExpectations: 'Sowing, weeding, and harvesting groundnuts (நிலக்கடலை விதைத்தல், களையெடுத்தல், அறுவடை செய்தல்)', workHours: '8 Hours (8 மணி நேரம்)', salary: 690, farmerEmail: 'manonmani.kulithalai@email.com', farmerPhone: '8998877658', farmerRating: 4.8, farmerImage: 'https://placehold.co/100x100.png?text=ம', farmerImageHint: 'woman harvesting groundnuts' },
  { farmerName: 'Ayyanar (அய்யனார்)', location: 'Kulithalai, Karur (குளித்தலை, கரூர்)', acres: 12, landDetails: 'Cattle Farm (மாட்டுப் பண்ணை)', workerExpectations: 'Preparing fodder and managing cattle shed (தீவனம் தயாரித்தல் மற்றும் மாட்டு கொட்டகை பராமரிப்பு)', workHours: '9 Hours (9 மணி நேரம்)', salary: 720, farmerEmail: 'ayyanar.kulithalai@email.com', farmerPhone: '8998877657', farmerRating: 4.5, farmerImage: 'https://placehold.co/100x100.png?text=அ', farmerImageHint: 'man with cattle feed' },
  { farmerName: 'Chitra (சித்ரா)', location: 'Kulithalai, Karur (குளித்தலை, கரூர்)', acres: 7, landDetails: 'Flower Garden (பூந்தோட்டம்)', workerExpectations: 'Plucking flowers for local market and temples (உள்ளூர் சந்தை மற்றும் கோவில்களுக்கு பூ பறித்தல்)', workHours: '6 Hours (6 மணி நேரம்)', salary: 580, farmerEmail: 'chitra.kulithalai@email.com', farmerPhone: '8998877656', farmerRating: 4.9, farmerImage: 'https://placehold.co/100x100.png?text=சி', farmerImageHint: 'woman with a basket of flowers' },
];

export default function WorkerDashboard() {
  const [isApplyDialogOpen, setApplyDialogOpen] = useState(false);
  const [selectedJob, setSelectedJob] = useState<JobPost | null>(null);

  const handleApplyClick = (job: JobPost) => {
    setSelectedJob(job);
    setApplyDialogOpen(true);
  };
  
  const jobsByDistrict = jobPosts.reduce((acc, job) => {
    const district = job.location.split(', ')[1].split(' (')[0];
    if (!acc[district]) {
      acc[district] = [];
    }
    acc[district].push(job);
    return acc;
  }, {} as Record<string, JobPost[]>);


  return (
    <div className="min-h-screen w-full bg-secondary/50">
      <DashboardHeader title="Worker Dashboard" userType="worker" />
      
      <main className="container mx-auto py-8">
        <h1 className="text-3xl font-bold mb-6 font-headline">Available Jobs (கிடைக்கும் வேலைகள்)</h1>
         {Object.entries(jobsByDistrict).map(([district, districtJobs]) => {
            const jobsByTaluk = districtJobs.reduce((acc, job) => {
                const taluk = job.location.split(', ')[0];
                if (!acc[taluk]) {
                    acc[taluk] = [];
                }
                acc[taluk].push(job);
                return acc;
            }, {} as Record<string, JobPost[]>);

            return (
                 <section key={district} className="mb-12">
                  <h2 className="text-2xl font-bold mb-4 font-headline border-b pb-2">{district}</h2>
                    <Accordion type="multiple" className="w-full space-y-4">
                        {Object.entries(jobsByTaluk).map(([taluk, talukJobs]) => (
                             <AccordionItem value={taluk} key={taluk} className="border bg-card rounded-lg">
                                <AccordionTrigger className="p-6 text-lg font-semibold hover:no-underline">
                                    <div className="flex items-center gap-3">
                                        <MapPin className="h-6 w-6 text-primary" />
                                        {taluk}
                                    </div>
                                </AccordionTrigger>
                                <AccordionContent className="p-6 pt-0">
                                    <div className="flex flex-col gap-4">
                                      {talukJobs.map((post, index) => (
                                        <Card key={index} className="flex flex-col sm:flex-row transition-all hover:shadow-md">
                                          <CardHeader className="flex-1 p-4">
                                            <CardTitle className="text-lg">{post.workerExpectations.split(' (')[0]}</CardTitle>
                                            <CardDescription className="flex items-center pt-1 text-sm">
                                              <Tractor className="mr-2 h-4 w-4" />
                                              {post.farmerName}
                                            </CardDescription>
                                             <div className="flex items-center text-xs text-muted-foreground pt-2">
                                              <Mountain className="mr-2 h-4 w-4" />
                                              <span>{post.acres} acres - {post.landDetails}</span>
                                            </div>
                                          </CardHeader>
                                          <CardContent className="flex flex-1 flex-col justify-center gap-2 border-t p-4 sm:border-l sm:border-t-0">
                                            <div className="flex items-center text-sm">
                                              <Clock className="mr-2 h-4 w-4 text-muted-foreground" />
                                              <span>Work Hours: {post.workHours}</span>
                                            </div>
                                            <div className="flex items-center text-sm font-semibold text-primary">
                                              <DollarSign className="mr-2 h-4 w-4" />
                                              <span>Salary: ₹{post.salary} / day</span>
                                            </div>
                                          </CardContent>
                                          <CardFooter className="flex items-center justify-center p-4 sm:border-l">
                                            <Button className="w-full sm:w-auto" onClick={() => handleApplyClick(post)}>Apply</Button>
                                          </CardFooter>
                                        </Card>
                                      ))}
                                    </div>
                                </AccordionContent>
                            </AccordionItem>
                        ))}
                    </Accordion>
                </section>
            );
        })}
      </main>

       {/* Apply for Job Dialog */}
      {selectedJob && (
         <Dialog open={isApplyDialogOpen} onOpenChange={setApplyDialogOpen}>
          <DialogContent className="sm:max-w-md">
            <DialogHeader>
              <div className="flex items-center gap-4">
                 <Avatar className="h-24 w-24">
                    <AvatarImage src={selectedJob.farmerImage} alt={selectedJob.farmerName} data-ai-hint={selectedJob.farmerImageHint} />
                    <AvatarFallback>{selectedJob.farmerName.charAt(0)}</AvatarFallback>
                  </Avatar>
                <div>
                  <DialogTitle className="text-2xl">{selectedJob.farmerName}</DialogTitle>
                   <DialogDescription>
                     Contact details for this job. (இந்த வேலைக்கான தொடர்பு விவரங்கள்.)
                   </DialogDescription>
                </div>
              </div>
            </DialogHeader>
            <div className="py-4 space-y-4">
                <div className="flex items-start">
                  <Tractor className="mr-3 mt-1 h-5 w-5 text-muted-foreground" />
                  <span>Farmer's Expectation: {selectedJob.workerExpectations}</span>
                </div>
               <div className="flex items-center">
                  <DollarSign className="mr-3 h-5 w-5 text-muted-foreground" />
                  <span>Salary: ₹{selectedJob.salary} / day (சம்பளம்: ₹{selectedJob.salary} / நாள்)</span>
                </div>
                <div className="flex items-center">
                    <Star className="mr-3 h-5 w-5 text-amber-400 fill-amber-400" />
                    <span>Farmer Rating: {selectedJob.farmerRating}/5.0 (விவசாயி மதிப்பீடு)</span>
                </div>
               <div className="flex items-center">
                  <Phone className="mr-3 h-5 w-5 text-muted-foreground" />
                  <a href={`tel:${selectedJob.farmerPhone}`} className="text-primary hover:underline">{selectedJob.farmerPhone}</a>
                </div>
                <div className="flex items-center">
                    <Mail className="mr-3 h-5 w-5 text-muted-foreground" />
                    <a href={`mailto:${selectedJob.farmerEmail}`} className="text-primary hover:underline">{selectedJob.farmerEmail}</a>
                </div>
            </div>
            <DialogFooter>
               <Button variant="outline" onClick={() => setApplyDialogOpen(false)}>Close (மூடு)</Button>
               <Button asChild>
                <a href={`tel:${selectedJob.farmerPhone}`}>
                  <Phone className="mr-2 h-4 w-4" />
                  Call (அழைக்க)
                </a>
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      )}
    </div>
  );
}
